export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SMS_VALIDATION = 'SMS_VALIDATION';
export const SMS_VALIDATION_SUCCESS= 'SMS_VALIDATION_SUCCESS';
export const SMS_VALIDATION_FAILURE= 'SMS_VALIDATION_FAILURE';
export const HANDLE_INPUT = "INPUT_CHANGED";
export const SEND_SMS = "SEND_SMS";
export const NEXT_INPUT = "NEXT_INPUT";
export const INPUT_ERROR="INPUT_ERROR";

